add aws_acc_num var usage

diff --git a/.github/workflows/infra.yml b/.github/workflows/infra.yml
--- a/.github/workflows/infra.yml
+++ b/.github/workflows/infra.yml
@@ -1,18 +1,18 @@
 name: infra
 on:
-  pull_request:
-  workflow_dispatch:
-      inputs:
-          terraform_job:
-              type: choice
-              description: Terraform
-              options:
-                  - plan
-                  - apply
-                  - destroy
+    pull_request:
+    workflow_dispatch:
+        inputs:
+            terraform_job:
+                type: choice
+                description: Terraform
+                options:
+                    - plan
+                    - apply
+                    - destroy
 env:
-  BRANCH_NAME: ${{github.base_ref || github.ref_name}}
-  TF_VAR_db_pass: ${{ secrets.db_pass }}
+    BRANCH_NAME: ${{github.base_ref || github.ref_name}}
+    TF_VAR_db_pass: ${{ secrets.db_pass }}
 permissions:
     contents: read
     id-token: write
@@ -37,23 +37,23 @@ jobs:
             - name: configure aws credentials
               uses: aws-actions/configure-aws-credentials@v4
               with:
-                  role-to-assume: arn:aws:iam::069363837566:role/github-tnote-terraform
+                  role-to-assume: arn:aws:iam::${{ vars.aws_acc_num }}:role/github-tnote-terraform
                   role-session-name: GitHub_to_AWS_via_FederatedOIDC
                   aws-region: ap-southeast-2
             - name: Setup Atmos
               uses: cloudposse/github-action-setup-atmos@1.0.2
               with:
-                atmos-version: 1.45.3
-                install-wrapper: false
-            
+                  atmos-version: 1.45.3
+                  install-wrapper: false
+
             - name: Validate branch
               run: |
-                if [[ $BRANCH_NAME == "env/"* ]]; then
-                  echo "Valid branch. Current branch is: $BRANCH_NAME"
-                else
-                  echo "Invalid branch. Branch must be under env/*"
-                  exit 1
-                fi
+                  if [[ $BRANCH_NAME == "env/"* ]]; then
+                    echo "Valid branch. Current branch is: $BRANCH_NAME"
+                  else
+                    echo "Invalid branch. Branch must be under env/*"
+                    exit 1
+                  fi
             - name: Set env
               run: echo "STACK=${BRANCH_NAME#env/}"  >> $GITHUB_ENV
 
